ecommerce_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres      # Ім'я контейнера (внутрішня мережа Docker)
      user: dwh_user
      password: dwh_pass
      port: 5432
      dbname: dwh
      schema: public      # Схема, куди dbt буде писати свої службові таблиці
      threads: 1