version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: dwh_postgres
    environment:
      POSTGRES_DB: dwh
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: dwh_pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dwh_user -d dwh"]
      interval: 10s
      retries: 5

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://dwh_user:dwh_pass@postgres:5432/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    # ПЕРЕВИЗНАЧАЄМО ВХІДНУ ТОЧКУ:
    # Це ігнорує всі перевірки Airflow і просто тримає контейнер увімкненим
    entrypoint: /bin/bash
    command: -c "sleep infinity"

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.3
    container_name: dbt
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./dbt:/usr/app/dbt
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
      DBT_HOST: postgres
      DBT_PORT: 5432
      DBT_USER: dwh_user
      DBT_PASSWORD: dwh_pass
      DBT_DBNAME: dwh
    # Те саме для dbt
    entrypoint: /bin/bash
    command: -c "sleep infinity"